---
title: "Data Import"
author: "Courtney Johnson"
date: "September 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Import FAS csv files

Import my first csv.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```

Import the pups data set also.

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## Look at data

Look at litters data. 

```{r}
head(litters_data)
tail(litters_data)

skimr::skim(litters_data)
```

## Learning Assessment; explore pups

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv", col_types = "diiiii")
pups_data = janitor::clean_names(pups_data)
head(pups_data)
tail(pups_data)
skimr::skim(pups_data)
```



## Other formats

Read in mlb data

```{r}
mlb_data = readxl::read_excel(path = "./data/mlb11.xlsx")

mlb_subset = readxl::read_excel(path = "./data/mlb11.xlsx",
                                range = "A1:E17")
```

Read in pulse data:

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```

## Compare with base R

```{r}
pups_readr = read_csv("./data/FAS_pups.csv")
pups_baser = read.csv("./data/FAS_pups.csv")

pups_readr
pups_baser

pups_readr$S
pups_baser$S
```

